---
title: "Examples"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{examples}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 7,
  fig.height = 4.5,
  fig.align = "center"
)
```

```{r setup}
library(ggplot2)
library(ggzip)
```

## Default Theme
```{r}
ggplot(mtcars, aes(x = mpg, y = disp)) +
  geom_point(size=3) +
  labs(title = "Displacement vs MPG")
```

## Load the Zip font
```{r}
library(showtext)
font_add_google(name = "Work Sans", family = "Work Sans")
showtext_auto()
```

## Zip Themes

### Minimal Theme

```{r}
ggplot(mtcars, aes(x = mpg, y = disp, color=as.factor(cyl))) +
  geom_point(size=3) + 
  theme_zip_minimal() +
  labs(title = "Displacement vs MPG") +
  theme(legend.position = "none")
```

### Classic Theme

```{r}
ggplot(mtcars, aes(x = mpg, y = disp, color=as.factor(cyl))) +
  geom_point(size=3) + 
  theme_zip_classic() + 
  labs(title = "Displacement vs MPG") +
  theme(legend.position = "none") +
  theme(legend.position = "none")
```

## Zip Color Palette

### Minimal Theme + Color Palette

```{r}
ggplot(mtcars, aes(x = mpg, y = disp, color=as.factor(cyl))) +
  geom_point(size=3) + 
  theme_zip_minimal() +
  labs(title = "Displacement vs MPG") +
  theme(legend.position = "none") +
  scale_color_zip(palette = "primary")
```

### Classic Theme + Color Palette

```{r}
ggplot(mtcars, aes(x = mpg, y = disp, color=as.factor(cyl))) +
  geom_point(size=3) + 
  theme_zip_classic() + 
  labs(title = "Displacement vs MPG") +
  theme(legend.position = "none") +
  theme(legend.position = "none") +
  scale_color_zip(palette = "primary")
```

### Color Spectrum

```{r}
col_seq <- function(pal = "cool") {
  cols <- zip_pal(pal)(10)
  
  n_seq <- seq_along(cols)
  image(n_seq, 1, as.matrix(n_seq), col = cols,
        xlab = "", ylab = "", xaxt = "n", yaxt = "n", bty = "n",
        main = paste("Color palette:", pal, " of Zip Co [10 levels]"))
  
  text(n_seq, 1, cols, col = "white", srt = 90)
}

col_seq("mixed")
```



